.TH PASSWORDMANAGER 1 "May 2024" "Version 1.0" "Password Manager Manual"
.SH NAME
passwordmanager \- A script to manage and generate passwords
.SH SYNOPSIS
.B passwordmanager.sh
[\fIoptions\fR]
.SH DESCRIPTION
.B passwordmanager.sh
is a script written by Filip Pawlicki for managing and generating passwords.

The script will prompt you to set a master password if it's the first time running. The master password is used to encrypt and decrypt the passwords. The encrypted passwords are stored in a file named \fB.passwords\fR in the same directory as the script. The script uses \fBzenity\fR for GUI dialogs and \fBxclip\fR to copy passwords to the clipboard. It also uses \fBopenssl\fR to encrypt and decrypt passwords and \fBawk\fR for parsing user input. Ensure that \fBzenity\fR, \fBxclip\fR, \fBopenssl\fR, and \fBawk\fR are installed on your system.

.SH OPTIONS
.TP
.B \-v
Display version and author information.
.TP
.B \-h
Display help.

.SH FUNCTIONS
.IP
\- Password encryption
.IP
\- Generating random passwords
.IP
\- Getting passwords
.IP
\- Updating passwords
.IP
\- Deleting passwords

.SH MENU OPTIONS
.IP
\- Save new password
.IP
\- Get password (Select from list)
.IP
\- Update password
.IP
\- Delete password
.IP
\- Change master password
.IP
\- Generate new password
.IP
\- Exit

.SH AUTHOR
Filip Pawlicki (s198371@student.pg.edu.pl)

.SH VERSION
1.0

.SH DATE
May 2024
